// sdk/prover.rs - Groth16 Proof Generation (Phase 9A.2)
//
// Per Bible Section 9A.2:
// - Wire existing Groth16 proof generation into the SDK
// - AgentIdentity generates proofs using leaf_secret from secure storage
// - Proof generation happens entirely on agent's machine
// - Nothing leaves the device. No server involved.
//
// CRITICAL: Uses CircomReduction, NOT LibsnarkReduction.
// Our membership_final.zkey was generated by circom which prepares powers of tau
// in Lagrange base. Using LibsnarkReduction would produce invalid proofs silently.
//
// THE CIRCUIT AND ZKEY ARE FROZEN. This module only wires them into the SDK.

use anyhow::{Result, anyhow};
use ark_bn254::{Bn254, Fr};
use ark_circom::{CircomBuilder, CircomConfig, CircomReduction};
use ark_ff::PrimeField;
use ark_groth16::{Groth16, ProvingKey};
use ark_serialize::{CanonicalDeserialize, CanonicalSerialize};
use ark_snark::SNARK;
use std::path::Path;
use std::fs::File;
use std::io::BufReader;

/// Proof generation result
#[derive(Debug, Clone)]
pub struct ProofResult {
    /// Groth16 proof bytes (serialized)
    pub proof_bytes: Vec<u8>,
    /// Merkle root (hex, 32 bytes)
    pub merkle_root: String,
    /// npub X coordinate (hex, 32 bytes - reconstructed from 4 limbs)
    pub npub_x: String,
    /// npub Y coordinate (hex, 32 bytes - reconstructed from 4 limbs)
    pub npub_y: String,
    /// Proof generation time in milliseconds
    pub proof_time_ms: u64,
}

/// Groth16 prover configuration
pub struct ProverConfig {
    /// Path to membership.wasm (witness calculator)
    pub wasm_path: String,
    /// Path to membership.r1cs (circuit constraints)
    pub r1cs_path: String,
    /// Path to membership_final.zkey (proving key)
    pub zkey_path: String,
}

impl ProverConfig {
    /// Create prover config from a circuits directory path
    /// Expects: {dir}/membership.wasm, {dir}/membership.r1cs, {dir}/membership_final.zkey
    pub fn from_circuits_dir<P: AsRef<Path>>(dir: P) -> Self {
        let dir = dir.as_ref();
        Self {
            wasm_path: dir.join("membership_js/membership.wasm").to_string_lossy().to_string(),
            r1cs_path: dir.join("membership.r1cs").to_string_lossy().to_string(),
            zkey_path: dir.join("membership_final.zkey").to_string_lossy().to_string(),
        }
    }
    
    /// Create prover config with explicit paths
    pub fn new(wasm_path: String, r1cs_path: String, zkey_path: String) -> Self {
        Self { wasm_path, r1cs_path, zkey_path }
    }
}

/// Merkle witness for proof generation
#[derive(Debug, Clone)]
pub struct MerkleWitness {
    /// Merkle siblings (20 elements, hex strings)
    pub siblings: Vec<String>,
    /// Path direction bits (20 elements, 0 or 1)
    pub path_bits: Vec<u8>,
}

/// Groth16 prover for membership proofs
pub struct MembershipProver {
    config: ProverConfig,
    proving_key: Option<ProvingKey<Bn254>>,
}

impl MembershipProver {
    /// Create a new prover with the given configuration
    pub fn new(config: ProverConfig) -> Self {
        Self {
            config,
            proving_key: None,
        }
    }
    
    /// Load the proving key from the zkey file
    /// This is expensive (~1-2 seconds) so it's done once at initialization
    pub fn load_proving_key(&mut self) -> Result<()> {
        let zkey_path = Path::new(&self.config.zkey_path);
        if !zkey_path.exists() {
            return Err(anyhow!("zkey file not found: {}", self.config.zkey_path));
        }
        
        // Load zkey using ark-circom's ZKey parser
        let file = File::open(zkey_path)?;
        let mut reader = BufReader::new(file);
        
        // ark-circom provides read_zkey which handles circom's zkey format
        let (proving_key, _) = ark_circom::read_zkey(&mut reader)?;
        
        self.proving_key = Some(proving_key);
        Ok(())
    }
    
    /// Generate a Groth16 proof
    /// 
    /// # Arguments
    /// * `leaf_secret` - The 5 BN254 field elements from AgentIdentity
    /// * `witness` - The Merkle witness (siblings and path_bits)
    /// 
    /// # Returns
    /// ProofResult containing proof bytes and public outputs (merkle_root, npub)
    pub fn generate_proof(
        &self,
        leaf_secret: &[Fr; 5],
        witness: &MerkleWitness,
    ) -> Result<ProofResult> {
        let start = std::time::Instant::now();
        
        // Validate inputs
        if witness.siblings.len() != 20 {
            return Err(anyhow!("Expected 20 siblings, got {}", witness.siblings.len()));
        }
        if witness.path_bits.len() != 20 {
            return Err(anyhow!("Expected 20 path_bits, got {}", witness.path_bits.len()));
        }
        
        // Check that proving key is loaded
        let proving_key = self.proving_key.as_ref()
            .ok_or_else(|| anyhow!("Proving key not loaded. Call load_proving_key() first."))?;
        
        // Build circom config
        let cfg = CircomConfig::<Bn254>::new(
            &self.config.wasm_path,
            &self.config.r1cs_path,
        )?;
        
        // Build the circuit with inputs
        let mut builder = CircomBuilder::new(cfg);
        
        // Set leaf_secret[5]
        for (i, elem) in leaf_secret.iter().enumerate() {
            builder.push_input(
                &format!("leaf_secret[{}]", i),
                bigint_from_fr(elem),
            )?;
        }
        
        // Set siblings[20]
        for (i, sibling_hex) in witness.siblings.iter().enumerate() {
            let sibling = parse_hex_to_bigint(sibling_hex)?;
            builder.push_input(
                &format!("siblings[{}]", i),
                sibling,
            )?;
        }
        
        // Set path_bits[20]
        for (i, &bit) in witness.path_bits.iter().enumerate() {
            builder.push_input(
                &format!("path_bits[{}]", i),
                num_bigint::BigInt::from(bit),
            )?;
        }
        
        // Build the circuit (generates witness internally)
        let circom = builder.build()?;
        
        // Get the public inputs from the circuit
        let public_inputs = circom.get_public_inputs()
            .ok_or_else(|| anyhow!("Failed to get public inputs"))?;
        
        // Generate the proof using Groth16 with CircomReduction
        // CRITICAL: We use the default which is CircomReduction for ark-circom
        let mut rng = ark_std::rand::thread_rng();
        let proof = Groth16::<Bn254, CircomReduction>::prove(proving_key, circom, &mut rng)?;
        
        // Serialize the proof
        let mut proof_bytes = Vec::new();
        proof.serialize_compressed(&mut proof_bytes)?;
        
        // Extract public outputs
        // Public outputs order: merkle_root, npub_x[4], npub_y[4]
        if public_inputs.len() != 9 {
            return Err(anyhow!(
                "Expected 9 public inputs (1 root + 4 npub_x + 4 npub_y), got {}",
                public_inputs.len()
            ));
        }
        
        let merkle_root = fr_to_hex(&public_inputs[0]);
        
        // Reconstruct npub_x from 4 limbs (64 bits each)
        let npub_x = limbs_to_hex(&public_inputs[1..5])?;
        
        // Reconstruct npub_y from 4 limbs (64 bits each)
        let npub_y = limbs_to_hex(&public_inputs[5..9])?;
        
        let elapsed = start.elapsed();
        
        Ok(ProofResult {
            proof_bytes,
            merkle_root,
            npub_x,
            npub_y,
            proof_time_ms: elapsed.as_millis() as u64,
        })
    }
}

/// Convert Fr to BigInt for circom input
fn bigint_from_fr(fr: &Fr) -> num_bigint::BigInt {
    let bytes = fr.into_bigint().to_bytes_be();
    num_bigint::BigInt::from_bytes_be(num_bigint::Sign::Plus, &bytes)
}

/// Parse hex string to BigInt
fn parse_hex_to_bigint(hex: &str) -> Result<num_bigint::BigInt> {
    let hex = hex.strip_prefix("0x").unwrap_or(hex);
    let bytes = hex::decode(hex)
        .map_err(|e| anyhow!("Invalid hex: {}", e))?;
    Ok(num_bigint::BigInt::from_bytes_be(num_bigint::Sign::Plus, &bytes))
}

/// Convert Fr to hex string (32 bytes, zero-padded)
fn fr_to_hex(fr: &Fr) -> String {
    let bytes = fr.into_bigint().to_bytes_be();
    // Ensure 32 bytes
    let mut padded = vec![0u8; 32];
    let start = 32 - bytes.len().min(32);
    padded[start..].copy_from_slice(&bytes[bytes.len().saturating_sub(32)..]);
    hex::encode(padded)
}

/// Reconstruct a 256-bit value from 4x64-bit limbs
/// Limbs are in little-endian order (limb[0] is least significant)
fn limbs_to_hex(limbs: &[Fr]) -> Result<String> {
    if limbs.len() != 4 {
        return Err(anyhow!("Expected 4 limbs, got {}", limbs.len()));
    }
    
    let mut result = [0u8; 32];
    
    for (i, limb) in limbs.iter().enumerate() {
        // Each limb is a 64-bit value
        let limb_bytes = limb.into_bigint().to_bytes_le();
        // Take first 8 bytes (64 bits)
        let limb_u64_bytes: [u8; 8] = limb_bytes[..8]
            .try_into()
            .map_err(|_| anyhow!("Invalid limb size"))?;
        
        // Place in result (little-endian: limb 0 at bytes 0-7, etc.)
        result[i * 8..(i + 1) * 8].copy_from_slice(&limb_u64_bytes);
    }
    
    // Result is little-endian, reverse for big-endian hex output
    result.reverse();
    Ok(hex::encode(result))
}

#[cfg(test)]
mod tests {
    use super::*;
    use ark_ff::UniformRand;
    
    #[test]
    fn test_fr_to_hex() {
        let mut rng = ark_std::rand::thread_rng();
        let fr = Fr::rand(&mut rng);
        let hex = fr_to_hex(&fr);
        assert_eq!(hex.len(), 64); // 32 bytes = 64 hex chars
    }
    
    #[test]
    fn test_parse_hex_to_bigint() {
        let hex = "0x123456789abcdef0";
        let bigint = parse_hex_to_bigint(hex).unwrap();
        assert!(bigint > num_bigint::BigInt::from(0));
    }
    
    #[test]
    fn test_prover_config_from_dir() {
        let config = ProverConfig::from_circuits_dir("/tmp/circuits/build");
        assert!(config.wasm_path.contains("membership.wasm"));
        assert!(config.r1cs_path.contains("membership.r1cs"));
        assert!(config.zkey_path.contains("membership_final.zkey"));
    }
}
