//! Witness generation for Groth16 proofs
//! 
//! The witness is generated by evaluating the circuit with private inputs.
//! 
//! Input layout (membership circuit):
//! - leaf_secret[8]: 8 × 32-bit values (256-bit secret)
//! - siblings[20]: 20 merkle siblings (depth 20)
//! - path_bits[20]: 20 path direction bits
//! 
//! Output layout:
//! - merkle_root: 1 field element
//! - npub_x[4]: 4 × 64-bit limbs
//! - npub_y[4]: 4 × 64-bit limbs
//! 
//! For now, witness generation requires calling the C++ calculator.
//! This module provides the interface and input preparation.

use ark_bn254::Fr;
use ark_ff::PrimeField;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::process::Command;
use std::path::Path;
use thiserror::Error;

#[derive(Error, Debug)]
pub enum WitnessError {
    #[error("Invalid input: {0}")]
    InvalidInput(String),
    #[error("Witness calculator not found: {0}")]
    CalculatorNotFound(String),
    #[error("Witness calculation failed: {0}")]
    CalculationFailed(String),
    #[error("IO error: {0}")]
    IoError(#[from] std::io::Error),
    #[error("Parse error: {0}")]
    ParseError(String),
}

/// Inputs for membership proof
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MembershipInputs {
    /// Leaf secret (256 bits as 8 × 32-bit values)
    pub leaf_secret: [u64; 8],
    /// Merkle siblings (depth 20)
    pub siblings: Vec<String>,
    /// Path direction bits
    pub path_bits: Vec<u8>,
}

impl MembershipInputs {
    /// Create from raw bytes
    pub fn from_bytes(
        secret: &[u8; 32],
        siblings: &[String],
        path_bits: &[u8],
    ) -> Result<Self, WitnessError> {
        if siblings.len() != 20 {
            return Err(WitnessError::InvalidInput(
                format!("Expected 20 siblings, got {}", siblings.len())
            ));
        }
        if path_bits.len() != 20 {
            return Err(WitnessError::InvalidInput(
                format!("Expected 20 path bits, got {}", path_bits.len())
            ));
        }
        
        // Split 32-byte secret into 8 × 32-bit chunks
        let mut leaf_secret = [0u64; 8];
        for i in 0..8 {
            let chunk = &secret[i * 4..(i + 1) * 4];
            leaf_secret[i] = u32::from_le_bytes(chunk.try_into().unwrap()) as u64;
        }
        
        Ok(Self {
            leaf_secret,
            siblings: siblings.to_vec(),
            path_bits: path_bits.to_vec(),
        })
    }
    
    /// Convert to JSON for witness calculator
    pub fn to_json(&self) -> Result<String, WitnessError> {
        let mut map = HashMap::<String, serde_json::Value>::new();
        
        // leaf_secret as array of strings
        let secret_strs: Vec<String> = self.leaf_secret.iter()
            .map(|v| v.to_string())
            .collect();
        map.insert("leaf_secret".into(), serde_json::json!(secret_strs));
        
        // siblings as array of decimal strings (from hex)
        let sibling_strs: Vec<String> = self.siblings.iter()
            .map(|hex| {
                // Remove 0x prefix and parse as hex
                let clean = hex.strip_prefix("0x").unwrap_or(hex);
                // Convert to decimal string
                if let Ok(bytes) = hex::decode(clean) {
                    // Take first 4 bytes as u32 (M31 field element)
                    if bytes.len() >= 4 {
                        let val = u32::from_le_bytes(bytes[0..4].try_into().unwrap());
                        val.to_string()
                    } else {
                        "0".to_string()
                    }
                } else {
                    "0".to_string()
                }
            })
            .collect();
        map.insert("siblings".into(), serde_json::json!(sibling_strs));
        
        // path_bits as array of strings
        let path_strs: Vec<String> = self.path_bits.iter()
            .map(|v| v.to_string())
            .collect();
        map.insert("path_bits".into(), serde_json::json!(path_strs));
        
        serde_json::to_string_pretty(&map)
            .map_err(|e| WitnessError::ParseError(e.to_string()))
    }
}

/// Witness generator using C++ calculator
pub struct WitnessCalculator {
    /// Path to C++ binary
    calculator_path: String,
    /// Path to .dat file
    dat_path: String,
}

impl WitnessCalculator {
    /// Create calculator with paths
    pub fn new(calculator_path: &str, dat_path: &str) -> Self {
        Self {
            calculator_path: calculator_path.to_string(),
            dat_path: dat_path.to_string(),
        }
    }
    
    /// Check if calculator binary exists
    pub fn is_available(&self) -> bool {
        Path::new(&self.calculator_path).exists() && Path::new(&self.dat_path).exists()
    }
    
    /// Generate witness from inputs
    /// 
    /// Returns witness as vector of field elements
    pub fn calculate(&self, inputs: &MembershipInputs) -> Result<Vec<Fr>, WitnessError> {
        if !self.is_available() {
            return Err(WitnessError::CalculatorNotFound(
                format!("Binary: {}, Dat: {}", self.calculator_path, self.dat_path)
            ));
        }
        
        // Write input JSON to temp file
        let input_json = inputs.to_json()?;
        let input_path = "/tmp/signedby_witness_input.json";
        let output_path = "/tmp/signedby_witness_output.wtns";
        
        std::fs::write(input_path, &input_json)?;
        
        // Run C++ calculator
        let output = Command::new(&self.calculator_path)
            .arg(input_path)
            .arg(output_path)
            .output()?;
        
        if !output.status.success() {
            let stderr = String::from_utf8_lossy(&output.stderr);
            return Err(WitnessError::CalculationFailed(stderr.to_string()));
        }
        
        // Read witness file
        let witness_bytes = std::fs::read(output_path)?;
        parse_witness_file(&witness_bytes)
    }
}

/// Parse .wtns witness file format
fn parse_witness_file(bytes: &[u8]) -> Result<Vec<Fr>, WitnessError> {
    // .wtns format:
    // - 4 bytes: magic "wtns"
    // - 4 bytes: version
    // - 4 bytes: num sections
    // - Section 1: field element size + prime
    // - Section 2: witness values
    
    if bytes.len() < 12 {
        return Err(WitnessError::ParseError("Witness file too short".into()));
    }
    
    // Check magic
    if &bytes[0..4] != b"wtns" {
        return Err(WitnessError::ParseError("Invalid witness magic".into()));
    }
    
    // Skip header, find witness section
    // For simplicity, assume standard layout and parse witness values
    let mut offset = 12;
    
    // Skip section 1 header
    // Section type (4 bytes) + section size (8 bytes)
    if bytes.len() < offset + 12 {
        return Err(WitnessError::ParseError("Missing section header".into()));
    }
    
    // Read section size
    let section1_size = u64::from_le_bytes(bytes[offset + 4..offset + 12].try_into().unwrap());
    offset += 12 + section1_size as usize;
    
    // Now at section 2 (witness values)
    if bytes.len() < offset + 12 {
        return Err(WitnessError::ParseError("Missing witness section".into()));
    }
    
    let section2_size = u64::from_le_bytes(bytes[offset + 4..offset + 12].try_into().unwrap());
    offset += 12;
    
    // Each witness value is 32 bytes (Fr element)
    let num_values = section2_size as usize / 32;
    let mut witness = Vec::with_capacity(num_values);
    
    for _ in 0..num_values {
        if bytes.len() < offset + 32 {
            break;
        }
        
        // Parse as little-endian
        let value_bytes: [u8; 32] = bytes[offset..offset + 32].try_into().unwrap();
        let fr = Fr::from_le_bytes_mod_order(&value_bytes);
        witness.push(fr);
        
        offset += 32;
    }
    
    Ok(witness)
}

#[cfg(test)]
mod tests {
    use super::*;
    
    #[test]
    fn test_membership_inputs() {
        let secret = [0u8; 32];
        let siblings: Vec<String> = (0..20).map(|_| "0x00".to_string()).collect();
        let path_bits: Vec<u8> = vec![0; 20];
        
        let inputs = MembershipInputs::from_bytes(&secret, &siblings, &path_bits).unwrap();
        assert_eq!(inputs.leaf_secret.len(), 8);
        
        let json = inputs.to_json().unwrap();
        assert!(json.contains("leaf_secret"));
    }
}
